import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { aiApi, workflowApi } from '../api/endpoints';
import PageHeader from '../components/PageHeader';

const EXAMPLES = [
  'Verify a PAN using Vendor A and, if it is valid, fetch GST details from Vendor B',
  'Validate an Aadhaar number and mask it before returning it',
  'Run OCR on a document, then check for fraud and match the face in parallel',
];

export default function AIAssistant() {
  const [description, setDescription] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');
  const navigate = useNavigate();

  async function generate() {
    setError('');
    setLoading(true);
    setResult(null);
    try {
      const { data } = await aiApi.generate(description);
      setResult(data.data);
    } catch (err) {
      setError(err.response?.data?.error?.message || err.message);
    } finally {
      setLoading(false);
    }
  }

  async function saveAsWorkflow() {
    const res = await workflowApi.create(result.definition, true);
    navigate(`/workflows/${res.data.data.id}/edit`);
  }

  return (
    <div style={{ padding: '28px 36px', maxWidth: 860 }}>
      <PageHeader
        title="AI Assistant"
        subtitle="Describe the integration you want in plain English — the agent drafts the workflow configuration for you."
      />

      <div className="card" style={{ marginBottom: 20 }}>
        <div className="field">
          <label className="label">What should this API do?</label>
          <textarea
            className="textarea"
            style={{ fontFamily: 'var(--font-body)' }}
            rows={3}
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="e.g. Verify a PAN using Vendor A and, if valid, fetch GST details from Vendor B"
          />
        </div>

        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 14 }}>
          {EXAMPLES.map((ex) => (
            <button key={ex} className="btn btn-ghost btn-sm" onClick={() => setDescription(ex)}>{ex}</button>
          ))}
        </div>

        <button className="btn btn-primary" onClick={generate} disabled={loading || description.trim().length < 8}>
          {loading ? 'Thinking…' : '✨ Generate workflow'}
        </button>

        {error && <div style={{ color: 'var(--rose)', fontSize: 13, marginTop: 12 }}>{error}</div>}
      </div>

      {result && (
        <div className="card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
            <div>
              <h3 style={{ fontSize: 15 }}>{result.definition.method} /run/{result.definition.slug}</h3>
              <span className="badge badge-indigo" style={{ marginTop: 6 }}>
                {result.source === 'llm' ? 'Generated by Claude' : 'Generated by rule-based fallback'}
              </span>
            </div>
            <button className="btn btn-primary" onClick={saveAsWorkflow}>Save as new workflow</button>
          </div>

          {result.lint && result.lint.issues.length > 0 && (
            <div style={{ marginBottom: 14 }}>
              <div className="label">Lint results</div>
              {result.lint.issues.map((issue, i) => (
                <div key={i} style={{ fontSize: 12.5, color: issue.level === 'error' ? 'var(--rose)' : 'var(--amber)', marginTop: 4 }}>
                  {issue.level === 'error' ? '✕' : '⚠'} {issue.message}
                </div>
              ))}
            </div>
          )}

          <div className="label">Generated definition</div>
          <pre className="mono" style={{ fontSize: 11.5, background: 'var(--ink-800)', padding: 14, borderRadius: 8, marginTop: 8, overflowX: 'auto', maxHeight: 420 }}>
            {JSON.stringify(result.definition, null, 2)}
          </pre>
        </div>
      )}
    </div>
  );
}
